name: Deploy Vite React to GCS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          npm ci || npm i
          npm run build

      - name: Auth with Google (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud (includes gsutil)
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure bucket website (idempotent)
        run: |
          gcloud storage buckets update gs://${{ secrets.GCS_BUCKET }} \
            --web-main-page-suffix=index.html \
            --web-error-page=index.html || true

      # อัปโหลดแบบ sync (ลบไฟล์เก่าที่ไม่มีแล้ว)
      - name: Upload to GCS (gsutil rsync)
        run: |
          gsutil -m rsync -r -d dist gs://${{ secrets.GCS_BUCKET }}

      # ตั้ง Cache-Control แบบเหมาะสมตามชนิดไฟล์
      - name: Set Cache-Control headers (safe)
        env:
          BUCKET: ${{ secrets.GCS_BUCKET }}
        run: |
          set -e

          # 1) HTML ทั้งหมด: no-cache (ป้องกัน stale shell)
          if gsutil -q ls gs://$BUCKET/*.html >/dev/null 2>&1; then
            gsutil -m setmeta -h "Cache-Control:no-cache, max-age=0, must-revalidate" gs://$BUCKET/*.html || true
          fi
          if gsutil -q ls gs://$BUCKET/**/*.html >/dev/null 2>&1; then
            gsutil -m setmeta -h "Cache-Control:no-cache, max-age=0, must-revalidate" gs://$BUCKET/**/*.html || true
          fi

          # 2) ไฟล์ asset ที่มี hash: cache ยาว + immutable
          if gsutil -q ls gs://$BUCKET/assets/** >/dev/null 2>&1; then
            gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" gs://$BUCKET/assets/** || true
          fi

          # 3) ไฟล์ static root ที่มักเปลี่ยนไม่บ่อย (แต่ไม่ควร immutable)
          for f in favicon.ico manifest.json site.webmanifest robots.txt apple-touch-icon.png; do
            if gsutil -q stat gs://$BUCKET/$f; then
              gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://$BUCKET/$f || true
            fi
          done

          # 4) เผื่อมี index.html อยู่ (ตั้งซ้ำอีกชั้น ไม่เป็นไร)
          if gsutil -q stat gs://$BUCKET/index.html; then
            gsutil -m setmeta -h "Cache-Control:no-cache, max-age=0, must-revalidate" gs://$BUCKET/index.html || true
          fi
