name: Deploy Vite React to GCS

on:
  push:
    branches: [ main ]  # เปลี่ยนเป็นสาขาที่คุณใช้

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # สำคัญสำหรับ OIDC/WIF

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Auth with Google (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure bucket website (safe if already set)
        run: |
          gcloud storage buckets update gs://${{ secrets.GCS_BUCKET }} \
            --web-main-page-suffix=index.html \
            --web-error-page=index.html || true

      - name: Upload to GCS
        run: |
          gcloud storage rsync --recursive --delete dist gs://${{ secrets.GCS_BUCKET }}

      - name: Set Cache-Control headers
        run: |
          gsutil -m setmeta -h "Cache-Control:no-cache" gs://${{ secrets.GCS_BUCKET }}/index.html || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" gs://${{ secrets.GCS_BUCKET }}/assets/** || true
