name: Deploy Vite React to GCS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      GCS_BUCKET_RAW: ${{ secrets.GCS_BUCKET }}           # เช่น skt-front (ไม่มี gs://, ไม่มีเครื่องหมายคำพูด)
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}       # เช่น peaceful-web-469207-h1
      GCP_CDN_URL_MAP: ${{ secrets.GCP_CDN_URL_MAP }}     # optional

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build
        run: |
          npm ci || npm i
          npm run build

      - name: Auth with Google (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud (includes gsutil)
        uses: google-github-actions/setup-gcloud@v2

      # --- Normalize + Validate + Ensure bucket exists ---
      - name: Verify/Create GCS bucket
        id: verify_bucket
        run: |
          set -euo pipefail

          raw="${GCS_BUCKET_RAW:-}"
          # ตัด gs://, ตัด / ท้าย, ตัดช่องว่าง/quote, บังคับเป็นตัวเล็ก
          raw="${raw#gs://}"
          raw="${raw%/}"
          # shellcheck disable=SC2001
          raw="$(echo "$raw" | tr '[:upper:]' '[:lower:]' | sed -E 's/^[[:space:]]+|[[:space:]]+$//g; s/^["'\'']+//; s/["'\'']+$//')"

          echo "Using bucket (normalized): $raw"
          if [ -z "$raw" ]; then
            echo "ERROR: GCS_BUCKET is empty after normalization"; exit 1
          fi

          # ตรวจตามกฎชื่อบัคเก็ต
          # - 3..63 ตัวอักษร
          # - เริ่ม/จบด้วย [a-z0-9]
          # - ใช้ได้เฉพาะ [a-z0-9._-]
          if [ ${#raw} -lt 3 ] || [ ${#raw} -gt 63 ] || ! echo "$raw" | grep -Eq '^[a-z0-9][a-z0-9._-]{1,61}[a-z0-9]$'; then
            echo "ERROR: Invalid bucket name after normalization: '$raw'"
            exit 1
          fi

          echo "BUCKET_NORMALIZED=$raw" >> "$GITHUB_OUTPUT"

          PROJECT="${GCP_PROJECT_ID:-}"
          if [ -z "$PROJECT" ]; then
            PROJECT="$(gcloud config get-value core/project || true)"
          fi
          if [ -z "$PROJECT" ]; then
            echo "ERROR: GCP_PROJECT_ID is empty and no active gcloud project set."; exit 1
          fi
          echo "Using project: $PROJECT"

          if ! gcloud storage buckets describe "gs://$raw" --project="$PROJECT" >/dev/null 2>&1; then
            echo "Bucket gs://$raw not found. Creating..."
            gcloud storage buckets create "gs://$raw" \
              --project="$PROJECT" \
              --location=ASIA-SOUTHEAST1 \
              --uniform-bucket-level-access
          else
            echo "Bucket gs://$raw exists."
          fi

          # ตั้งหน้าเว็บ (idempotent)
          gcloud storage buckets update "gs://$raw" \
            --web-main-page-suffix=index.html \
            --web-error-page=index.html || true

      # --- Upload with correct Cache-Control at upload time ---
      - name: Upload index.html (no-cache) and assets (immutable)
        env:
          BUCKET: ${{ steps.verify_bucket.outputs.BUCKET_NORMALIZED }}
        run: |
          set -euo pipefail
          echo "Using bucket: $BUCKET"

          test -f dist/index.html || { echo "dist/index.html not found. Did build fail?"; exit 1; }

          # ลบ assets เก่า กันไฟล์ตกค้าง
          gsutil -m rm -r "gs://$BUCKET/assets/**" 2>/dev/null || true

          # อัปโหลด index.html (no-cache)
          gsutil -h "Cache-Control:no-cache" cp "dist/index.html" "gs://$BUCKET/index.html"

          # อัปโหลด assets (immutable + cache ยาว)
          if [ -d "dist/assets" ]; then
            gsutil -m -h "Cache-Control:public, max-age=31536000, immutable" cp -r "dist/assets/*" "gs://$BUCKET/assets/"
          else
            echo "WARN: dist/assets not found (Vite may have inlined assets)"
          fi

      # --- Optional: Invalidate Cloud CDN ---
      - name: Invalidate Cloud CDN (optional)
        if: ${{ env.GCP_CDN_URL_MAP != '' }}
        run: |
          set -euo pipefail
          echo "Invalidating CDN cache for URL Map: ${GCP_CDN_URL_MAP}"
          gcloud compute url-maps invalidate-cdn-cache "${GCP_CDN_URL_MAP}" --path "/*" --quiet