name: Deploy to GCS (amc-front)

on:
  push:
    branches: [ main ]   # ถ้าใช้สาขาอื่น เปลี่ยนตรงนี้

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build (Vite/React)
        run: npm run build   # จะได้โฟลเดอร์ dist/

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload to GCS
        run: |
          gsutil -m rsync -r -d ./dist gs://amc-front
          gsutil web set -m index.html -e index.html gs://amc-front
