name: Deploy Vite React to GCS

on:
  push:
    branches: [ main ]   # เปลี่ยนตามสาขาที่คุณใช้

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write     # จำเป็นสำหรับ WIF (OIDC)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Auth with Google (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud (includes gsutil)
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure bucket website (idempotent)
        run: |
          gcloud storage buckets update gs://${{ secrets.GCS_BUCKET }} \
            --web-main-page-suffix=index.html \
            --web-error-page=index.html || true

      # ---- อัปโหลดแบบ "sync จริงๆ" และลบไฟล์ที่ไม่ใช้แล้ว (-d) ----
      - name: Upload to GCS (gsutil rsync)
        run: |
          gsutil -m rsync -r -d dist gs://${{ secrets.GCS_BUCKET }}

      # ---- ปรับ cache: index.no-cache, assets immutable ----
      - name: Set Cache-Control headers
        run: |
          gsutil -m setmeta -h "Cache-Control:no-cache" gs://${{ secrets.GCS_BUCKET }}/index.html || true
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" gs://${{ secrets.GCS_BUCKET }}/assets/** || true
