name: Deploy Vite React to GCS

on:
  push:
    branches: [ main ]   # เปลี่ยนตามสาขาที่ใช้

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write     # จำเป็นสำหรับ WIF (OIDC)

    env:
      GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
      # (ทางเลือก) ตั้ง SECRET นี้ถ้าเสิร์ฟผ่าน Cloud CDN (Backend Bucket/Service + URL Map)
      CDN_URL_MAP: ${{ secrets.GCP_CDN_URL_MAP }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci || npm i
          npm run build

      - name: Auth with Google (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud (includes gsutil)
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure bucket website (idempotent)
        run: |
          gcloud storage buckets update gs://$GCS_BUCKET \
            --web-main-page-suffix=index.html \
            --web-error-page=index.html || true

      # --- อัปโหลดแบบกำหนด Cache-Control ตั้งแต่ตอนอัปโหลด ---
      # ลบ assets เก่าออก (กันไฟล์ตกค้าง) แล้วอัปโหลดใหม่ด้วย header ที่ถูกต้อง
      - name: Upload index.html (no-cache) and assets (immutable)
        run: |
          # ลบโฟลเดอร์ assets เก่า (ถ้ามี)
          gsutil -m rm -r gs://$GCS_BUCKET/assets || true

          # อัปโหลด index.html พร้อมหัวข้อ Cache-Control:no-cache
          # (เบราว์เซอร์จะเช็คไฟล์นี้ใหม่ทุกครั้ง แล้วจะชี้ไปหาไฟล์ asset ชื่อ-hash ล่าสุด)
          gsutil -h "Cache-Control:no-cache" cp dist/index.html gs://$GCS_BUCKET/index.html

          # อัปโหลด assets ทั้งโฟลเดอร์ และตั้ง Cache-Control ยาว + immutable
          # (ไฟล์จาก Vite มีชื่อแบบ hashed อยู่แล้ว เปลี่ยนโค้ด = เปลี่ยนชื่อไฟล์ = โหลดใหม่แน่นอน)
          gsutil -m -h "Cache-Control:public, max-age=31536000, immutable" rsync -r dist/assets gs://$GCS_BUCKET/assets

      # --- (ทางเลือก) ถ้าเสิร์ฟผ่าน Cloud CDN: เคลียร์ cache หลังอัปโหลด ---
      - name: Invalidate Cloud CDN (optional)
        if: ${{ env.CDN_URL_MAP != '' }}
        run: |
          gcloud compute url-maps invalidate-cdn-cache "$CDN_URL_MAP" --path "/*" --quiet
