name: Deploy Vite React to GCS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      GCS_BUCKET_RAW: ${{ secrets.GCS_BUCKET }}           # e.g. skt-front (ไม่ต้องมี gs://)
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}       # e.g. peaceful-web-469207-h1
      GCP_CDN_URL_MAP: ${{ secrets.GCP_CDN_URL_MAP }}     # optional

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build
        run: |
          npm ci || npm i
          npm run build

      - name: Auth with Google (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud (includes gsutil)
        uses: google-github-actions/setup-gcloud@v2

      # --- Normalize bucket & ensure it exists ---
      - name: Verify/Create GCS bucket
        id: verify_bucket
        run: |
          set -euo pipefail

          # normalize: strip gs:// if user put it in secret
          BUCKET="${GCS_BUCKET_RAW}"
          BUCKET="${BUCKET#gs://}"
          echo "BUCKET_NORMALIZED=$BUCKET" >> $GITHUB_OUTPUT
          echo "Using bucket: $BUCKET"

          # find project id (prefer secret; fallback to gcloud active)
          PROJECT="${GCP_PROJECT_ID:-}"
          if [ -z "$PROJECT" ]; then
            PROJECT="$(gcloud config get-value core/project || true)"
          fi
          if [ -z "$PROJECT" ]; then
            echo "ERROR: GCP_PROJECT_ID is empty and no active gcloud project set."
            exit 1
          fi
          echo "Using project: $PROJECT"

          # create bucket if missing (choose a region you want)
          if ! gcloud storage buckets describe "gs://$BUCKET" --project="$PROJECT" >/dev/null 2>&1; then
            echo "Bucket gs://$BUCKET not found. Creating..."
            gcloud storage buckets create "gs://$BUCKET" \
              --project="$PROJECT" \
              --location=ASIA-SOUTHEAST1 \
              --uniform-bucket-level-access
          else
            echo "Bucket gs://$BUCKET exists."
          fi

          # website settings (idempotent)
          gcloud storage buckets update "gs://$BUCKET" \
            --web-main-page-suffix=index.html \
            --web-error-page=index.html || true

      # --- Upload with correct Cache-Control at upload time ---
      - name: Upload index.html (no-cache) and assets (immutable)
        env:
          BUCKET: ${{ steps.verify_bucket.outputs.BUCKET_NORMALIZED }}
        run: |
          set -euo pipefail

          echo "Using bucket: $BUCKET"

          test -f dist/index.html || { echo "dist/index.html not found. Did build fail?"; exit 1; }

          # remove old assets to avoid orphans
          gsutil -m rm -r "gs://$BUCKET/assets/**" 2>/dev/null || true

          # upload index.html with no-cache (always revalidate)
          gsutil -h "Cache-Control:no-cache" cp "dist/index.html" "gs://$BUCKET/index.html"

          # upload assets with long cache + immutable (Vite hashed filenames)
          if [ -d "dist/assets" ]; then
            gsutil -m -h "Cache-Control:public, max-age=31536000, immutable" cp -r "dist/assets/*" "gs://$BUCKET/assets/"
          else
            echo "WARN: dist/assets not found (Vite may have inlined assets)"
          fi

      # --- (Optional) Invalidate Cloud CDN if you front this bucket with CDN ---
      - name: Invalidate Cloud CDN (optional)
        if: ${{ env.GCP_CDN_URL_MAP != '' }}
        run: |
          set -euo pipefail
          echo "Invalidating CDN cache for URL Map: ${GCP_CDN_URL_MAP}"
          gcloud compute url-maps invalidate-cdn-cache "${GCP_CDN_URL_MAP}" --path "/*" --quiet
