name: Deploy Vite React to GCS

on:
  push:
    branches: [ main ]   # เปลี่ยนตามสาขาที่ใช้

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write     # จำเป็นสำหรับ WIF (OIDC)

    env:
      GCS_BUCKET: ${{ secrets.GCS_BUCKET }}          # เช่น skt-front
      GCP_CDN_URL_MAP: ${{ secrets.GCP_CDN_URL_MAP }} # ชื่อ URL Map (ถ้าใช้ Cloud CDN ใส่ใน Secrets)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build
        run: |
          npm ci || npm i
          npm run build

      - name: Auth with Google (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud (includes gsutil)
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure bucket website (idempotent)
        run: |
          set -euo pipefail
          if [ -z "${GCS_BUCKET:-}" ]; then
            echo "ERROR: secrets.GCS_BUCKET is empty"; exit 1
          fi
          gcloud storage buckets update "gs://${GCS_BUCKET}" \
            --web-main-page-suffix=index.html \
            --web-error-page=index.html || true

      # === อัปโหลด: ตั้ง Cache-Control ให้ถูกตั้งแต่มืออัป ===
      - name: Upload index.html (no-cache) and assets (immutable)
        run: |
          set -euo pipefail

          echo "Using bucket: ${GCS_BUCKET}"
          test -n "${GCS_BUCKET}"

          # ตรวจไฟล์ build
          test -f dist/index.html || { echo "dist/index.html not found. Did build fail?"; exit 1; }

          # ลบ assets เก่า (ถ้ามี) - ป้องกันไฟล์ตกค้าง
          gsutil -m rm -r "gs://${GCS_BUCKET}/assets/**" 2>/dev/null || true

          # อัปโหลด index.html พร้อม no-cache (เบราว์เซอร์จะเช็คใหม่ทุกครั้ง)
          gsutil -h "Cache-Control:no-cache" cp "dist/index.html" "gs://${GCS_BUCKET}/index.html"

          # อัปโหลด assets ทั้งหมด พร้อม cache-control ยาว + immutable
          if [ -d "dist/assets" ]; then
            # ปลายทางต้องลงท้ายด้วย / เพื่อให้เป็นไดเรกทอรี
            gsutil -m -h "Cache-Control:public, max-age=31536000, immutable" cp -r "dist/assets/*" "gs://${GCS_BUCKET}/assets/"
          else
            echo "WARN: dist/assets not found (Vite may have inlined assets)"
          fi

      # === (ทางเลือก) ใช้ Cloud CDN อยู่หรือไม่ ถ้าใช้อยู่ให้เคลียร์ cache ===
      - name: Invalidate Cloud CDN (optional)
        if: ${{ env.GCP_CDN_URL_MAP != '' }}
        run: |
          set -euo pipefail
          echo "Invalidating CDN cache for URL Map: ${GCP_CDN_URL_MAP}"
          gcloud compute url-maps invalidate-cdn-cache "${GCP_CDN_URL_MAP}" --path "/*" --quiet
